name: LegendaryArmor
main: com.enjin.devection.main.Main
version: 1.0.2

commands:
  legend:
    description: Admin command only.

permissions:
  legendary.give:
    description: Gives the player the ability to act as the donation shop and give players legendary equipment.